# Generated by Django 4.0.1 on 2022-02-16 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='articulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=70)),
                ('cantidad', models.IntegerField(null=True)),
                ('precio', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_created=True)),
                ('nombre_articulo_venidio', models.CharField(max_length=70)),
                ('unidades_vendidas', models.IntegerField(null=True)),
                ('ganancia', models.FloatField(null=True)),
            ],
        ),
    ]
