# Generated by Django 4.0.1 on 2022-02-18 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('control_inventario', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='venta',
            old_name='nombre_articulo_venidio',
            new_name='nombre_articulo_vendido',
        ),
    ]
